- ros_topic_name: "/joints/fin_1_1/cmd_pos"
  gz_topic_name: "/model/fish_model/joint/fin_1_1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"

- ros_topic_name: "/joints/fin_1_1_circular/cmd_pos"
  gz_topic_name: "/model/fish_model/joint/fin_1_1_circular_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"

